name: TEI Publisher CI and Docker Snapshots

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
      - ci-test

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*
  
  pull_request:
    branches: [ master ]

  workflow_dispatch:

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: teipublisher

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Build docker image
        run: docker build -t exist-db -f Dockerfile .
      - name: Start docker image
        run: docker run --publish 8080:8080 --name db --detach exist-db
      - name: Run npm install
        run: npm install
      - name: Run tests
        run: npm test
      - name: Retrieve eXist log
        if: failure()
        run: docker cp db:/exist/logs/exist.log .
      - name: Publish log as artifact
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: exist.log
          path: ./exist.log
      - name: Stop docker
        run: docker stop db
